- fel.c
The SCTLR bits are somewhat different because the V bit is set
to 0 on A64 (Low exception vectors, base address 0x00000000) and
the UNK bit (Reads of this bit return an UNKNOWN value) is also not
the same as on the other SoCs. So the SCTLR check can be relaxed.
Changes in v2:
- Because the SRAM A and SRAM C reside back-to-back in the address
space, it is possible to use 40 KiB of SRAM by the SPL for its
code+data+stack. So the FEL backup storage is moved from 0x18000
to 0x1A000 to support this.
Signed-off-by: Siarhei Siamashka <siarhei.siamashka@gmail.com>
> fel: Add fel spl command support for Allwinner A64

- script.h
- script_bin.c
- script_fex.c
I'm currently experimenting with functional tests that do a "`fex2bin` + `bin2fex` cycle" on all FEX files from [sunxi-boards](https://github.com/linux-sunxi/sunxi-boards). In doing that, two minor problems with the current code showed up. This pull request addresses those.
> fexc fixes

- Makefile
- README.md
- nand-image-builder.c
Generating raw NAND images is particularly useful for boot0 images
creation since the mainline driver is not supporting the funky layout
used by Allwinner's ROM code to load the boot0 binary from NAND.
This tools also allows one to generate raw images for 'normal' partitions
so that they can be flashed before soldering on the NAND on the board
(using a regular NAND programmer).
The tool takes care of generating ECC bytes and randomizing data as
expected by the NAND controller, and re-arranging the ECC/data sections
correctly.
Signed-off-by: Boris Brezillon <boris.brezillon@free-electrons.com>
> Add a tool to generate raw NAND images

- include/portable_endian.h
Hello,
This patch fix building on FreeBSD.
> Fix building on FreeBSD

- fel.c
The patch represents the sunxi-tools side of [this U-Boot change](http://git.denx.de/?p=u-boot.git;a=commitdiff;h=320e0570e67efbd093d7750655a758c66e9d5528), and allows our FEL utility to pass environment data in a _uEnv.txt_-compatible format to a current U-Boot version (v2016.09 or later).
___
For example, use your text editor to save a _my.env_ file with
```
#=uEnv
myvar=world
bootcmd=echo "Hello $myvar."
```
and then test it with
`./sunxi-fel uboot u-boot-sunxi-with-spl.bin write 0x43100000 my.env`
You should see U-Boot's autoboot print the corresponding message and drop you to the prompt, proving that you have successfully overwritten the default "bootcmd".
> fel: Add the ability to pass uEnv-style data via FEL

- Makefile
The previous commit had introduced a new build rule that made
sunxi-pio always (cross-)compile as part of TARGET_TOOLS. This
originated from a misunderstanding, and is wrong - sunxi-pio
should be part of TOOLS instead.
sunxi-pio is a "dual mode" utility. When run natively on a sunxi
SoC, it can mmap() and manipulate the PIO registers directly. But
it also supports file-based operation, to be used in conjunction
with sunxi-fel (after uploading fel-pio.bin thunk code). This
should work over USB from non-sunxi hosts, and thus puts sunxi-pio
in the TOOLS category. See the fel-gpio shell script for details.
Signed-off-by: Bernhard Nortmann <bernhard.nortmann@web.de>
> Makefile: Revert sunxi-pio change from 209633a

- fel.c
- uart0-helloworld-sdboot.c
So far, only basic FEL functions (retrieving BROM version and SID) and _uart0-helloworld_ functionality have been tested.
> [Experimental] Add initial H5 support

- .travis.yml
- Makefile
- tests/Makefile
- tests/fextest.sh
- tests/patches/a-star_kv49l.patch
- tests/test_all_fex.sh
- tests/test_bin2fex_corner_cases.sh
- tests/test_fex2bin_corner_cases.sh
- tests/unify-fex.c
My goal for this series is to implement automated functional tests for `sunxi-fexc`, to ensure that all `.fex` files from the [sunxi-boards](https://github.com/linux-sunxi/sunxi-boards) repository can be compiled to binary format (_fex2bin_) and decompiled back (_bin2fex_) from `.bin` sucessfully.
I'll gradually amend the pull request, to check that the Travis CI status is fine after each commit.
---
[v1](https://github.com/linux-sunxi/sunxi-tools/commits/21461d5a0ebc8f35cd331003177eb7a61b747dd1): Initial version
> Extend continous integration by adding tests framework

- soc_info.c
The SID block in the A80 is at 0x01c0e000, with the e-fuses we care
about at offset 0x200 within the block.
Signed-off-by: Chen-Yu Tsai <wens@csie.org>
> fel: Add SID register address for A80

- fel.c
This allows code to be possibly reused, and is keeping better focus on the actual FEL functionality in `fel.c`.
---
Changes in [v1](https://github.com/linux-sunxi/sunxi-tools/commits/959de2eddb1f20f5b6ab2cbdf9f087ef6a6ea183): Initial version
Changes in [v2](https://github.com/linux-sunxi/sunxi-tools/commits/02faa6669622b07ef23af514af2499fb0fac182f):
- rebased on current master (9febb55)
- picked up the suggestion to incorporate _soc_sram_info_ (and FEL version data) into the handle
> Make use of FEL library to implement device enumeration and selection by SID

- fel.c
- soc_info.c
- soc_info.h
A one time programmable secure bit in the eFUSE radically changes the boot behaviour on some SoCs (H3/A64/H64). A new bootloader header format https://linux-sunxi.org/TOC0 replaces the old eGON.BT0. Also the FEL handler starts as non-secure and has no access to a lot of resources (SID, SRAM A2, etc.). Fortunately a workaround to switch FEL into the secure mode exists and these patches implement it.
> fel: SMC workaround for the Allwinner SoCs with the secure bit set in eFUSE

- fel.c
The version 2 of SPL added the possibility to add a device tree name in
the header, with adding some pad and using a reserved word.
As FEL boot currently doesn't need the device tree name, directly raise
the maximum supported version number to 2.
Signed-off-by: Icenowy Zheng <icenowy@aosc.io>
> fel: enable support for v2 SPL

- fel.c
Every addition of a new feature to the SPL header currently requires us
to update the FEL tool, to teach it about the new supported maximum
value. Many times the FEL tool doesn't really care, but complains
anyway - and refuses to load.
Let's introduce semantic versioning [1] for this field, where backwards
compatible additions just increase a minor number, but incompatible
changes require bumping the major version.
We have 8 bits for the SPL header version, let's split this to have 3 bits
for the major and 5 bit for the minor version number.
[1] https://semver.org
Signed-off-by: Icenowy Zheng <icenowy@aosc.io>
=========================
As the semantic versioning of SPL header is already accepted by
mainline U-Boot 2018.11, and the header …
> FEL: introduce semantic versioning for SPL header

- fel.c
- soc_info.c
- soc_info.h
The watchdog register isn't in the same place, nor uses the same values
to trigger a reset.
Signed-off-by: Karl Palsson <karlp@tweak.net.au>
Incomplete as far as filling in the structure for all the socs, if there's support for this, I can go and check more datasheets, but I didn't want to go and do all that datasheet trawling up front.  I only have a h3 board locally to test with unfortunately.  Inspiration from https://linux-sunxi.org/FEL#Tips_and_tricks
> Provide a wrapper for reset via watchdog

- fel-spiflash.c
This is a trivial fix, it just adds the A10 to the supported list. I've tested it and was able to successfully read the entire SPI flash of the device, but did not try writing yet.
> Add support for reading A10 SPI flash

- fel-spiflash.c
The Allwinner V3s SoC have the same SPI0 pinmux configuration, SPI clock
configuration and SPI controller (base address and the controller) with
H3.
Add spiflash support for it.
Signed-off-by: Icenowy Zheng <icenowy@aosc.io>
> spi: add support for V3s SoC

- fel-spiflash.c
Add the JEDEC manufacturer ID for Eon to the list of recognized
vendors, also add the EN25QH series to the list of supported chips.
Those chips are used on some internal boards with V831 from Sipeed now,
but the chips themselves are widely available on the market. Tag the
struct definition with the member names on the way to improve readability
of the SPI flash chip description.
Signed-off-by: Icenowy Zheng <icenowy@aosc.io>
> fel: SPI: add Eon support

- soc_info.c
As per the wiki[1] set ttbr0 to 0x44000 to enable the MMU. Transfer
speed is increased from 191KB/s to ~800KB/s which is handy when
transferring larger kernels and root filesystems.
Tested on a custom H8/A83T board.
[1] https://linux-sunxi.org/FEL/USBBoot
> fel: enable A83T MMU

- fel-spiflash.c
This PR fixes a typo which renders SPI flash functions unable to use for most devices.
Fixes #143.
Signed-off-by: Nazım Gediz Aydındoğmuş <gedizaydindogmus@gmail.com>
> spi: fix GPIO base address

- meminfo.c
Signed-off-by: Danny Milosavljevic <dannym@scratchpost.org>
sys/io.h has been removed in glibc 2.30.
https://sourceware.org/legacy-ml/libc-alpha/2019-08/msg00029.html
* On 32-bit Arm, support for the port-based I/O emulation and the <sys/io.h>
header have been removed.
It's easy to just directly access--so I did that...
> meminfo: Replace sys/io.h by direct register accesses.

- soc_info.c
The "wdreset" command so far only covered a few SoCs.
Add the watchdog data for the other ones as well.
> wdreset: Add remaining SoCs

- fel-spiflash.c
The H616 SPI is very similar to the H6, only differs in the GPIOs
(again).
Add the SoC-ID at the right places and add the GPIOs according to the
manual.
Tested on OrangePi Zero 2.
> spi: Add H616 support

- Makefile
- fel.c
- fel_lib.c
- fel_lib.h
- fit_image.c
- fit_image.h
This adds support for the "uboot" command to deal with a FIT image, as used on the 64-bit U-Boot builds. Together with the preliminary [64-bit U-Boot FEL support](https://lists.denx.de/pipermail/u-boot/2020-November/433083.html) this allows to bootstrap 64-bit boards with a simple:
`sunxi-fel uboot u-boot-sunxi-with-spl.bin`
This adds a build dependency to libfdt for sunxi-fel. We could make this optional, if this becomes a problem. I am open to suggestions on how to best autodetect this in the Makefile (there are some try-build macros in other projects we can copy from).
> sunxi-fel FIT image support

- README.md
There are two more dependencies in addition to libusb and pkgconfig, which
are libz and libfdt. Tell about them and give an example command to install
the packages through apt.
Signed-off-by: Nazım Gediz Aydındoğmuş <gedizaydindogmus@gmail.com>
> README: Add more information about other requirements

- Makefile
In cross-build situations this allows for `«triplet»-pkg-config` to be passed
in so that target libraries are used instead of host ones.
Unless `PKG_CONFIG` is overridden by the person doing the build then there is
no semantic change.
> Makefile: Specify `pkg-config` via a variable.

- fit_image.c
- nand-part.c
Two build fixes, one for newer GCCs (resolves #161), and one for some non-standard setup (couldn't reproduce, but see the problem), resolves #158.
> nandpart and fit-image build fixes

- Makefile
- sunxi-fel.1
So far the output of "sunxi-fel -h" was the only source of information
about sunxi-fel's command line parameters, and the description was
rather terse.
Add a manpage that describes the purpose of sunxi-fel and its options it
a bit more detail.
Amend the Makefile to install the manpage into the usual location.
> sunxi-fel: add manpage

- tests/Makefile
- tests/fextest.sh
- tests/test_all_fex.sh
- tests/test_bin2fex_corner_cases.sh
- tests/test_fex2bin_corner_cases.sh
These files were all originally by Bernhard in 2016 via these commits:
8445d71 unify-fex: Use int64_t and portable format specifiers for its output
f957f89 fextest: Add a dedicated rule for (CI-)testing sunxi-boards
6ec3876 tests: Improve code coverage by testing corner cases
cd5a0a3 tests: Improve on testing fexc
5cbb0c9 tests: Introduce a basic testing framework
and have not otherwise been touched. The header was added to unify-fex.c when
it was added in cd5a0a3303cb ("tests: Improve on testing fexc") but not to the
other files.
The license in unify-fex.c is the GPLv2+ which corresponds to the content of
LICENSE.md both at the time and now. I think therefore that it is appropriate
to duplicate the header into the other files (changing only the character used
for comments to suit)
--- 
I …
> Add license header to tests/*

- fel_lib.c
- soc_info.c
- soc_info.h
- uart0-helloworld-sdboot.c
This PR contains V853 support. (It comes even before V853 document release...)
V853 BROM enables I-Cache, but without FEL write command invalidating it, which makes uploading different thunks to the same address not working. It's currently worked around by disabling I-Cache.
In addition, V853 has a GPIO controller with a new register map (the same with D1), support for this GPIO controller is also added to uart0-helloworld-sdboot.
> V853 support

- soc_info.c
- uart0-helloworld-sdboot.c
This adds support for the Allwinner V5, which is close to the H6, but with 32-bit cores.
Also basic support for the R528/T113, which is the same SoC as the RISC-V D1 (even using the same SoC ID), but with that RISC-V core disabled. Proper D1 support requires much more work to support non-ARM code uploads.
Also includes uart0 hello world support for both SoCs.
> Allwinner V5 and R528/T113 support

- soc_info.c
- uart0-helloworld-sdboot.c
This adds support for the Allwinner A63, which is almost same as H6, but with different DRAM controller (maybe Designwire ?), and different interface.
The DRAM controller on A63 is closed to T7.
Also includes uart0 hello world support for this SoCs.
> Add A63 support

- Makefile
- uart0-helloworld-sdboot.c
The F1C100s series of SoCs has some subtle differences in its UART setup:
- The UART is at a previously unused address.
- The base clock is not APB2, but APB1.
- The input clock is not 24 MHz, but CPU clock / 2 / 2.
- The clock and reset gates are different bits at different addresses.
Add support for all those differences, tied to the F1C100s SoC ID.
> uart0-helloworld-sdboot: add support for F1C100s

- fel.c
- fel_lib.c
- fel_lib.h
- soc_info.c
- soc_info.h
A sample output from allwinner T3:
```console
$ ./sunxi-fel sid-dump
chipid          1300000c 02404700 79350400 5c761e0c
in              00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
ssk             00000000 00000000 00000000 00000000
thermal         08320834
ft_zone         00000000 00000000
tvout           010002b0 00f7029b 00f9029f 00fb02a5
rssk            00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
hdcp_hash       00000000 00000000 00000000 00000000
reserved        00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
```
> fel: Introduce 'sid-dump'

- fel.c
- fel_lib.c
- fel_lib.h
- soc_info.c
- sunxi-fel.1
- thunks/sid_read_root.S
- thunks/sid_read_root.h
Add some bits that were missing from the just merged sid-dump feature:
- support for the H3 register access work around
- maps for other SoCs
- documentation
@qianfan-Zhao @smaeul please have a look!
> Complete SID dump

- soc_info.c
The `generic_2k_sid_maps`, describing the SID sections for chips where we don't have any specific information yet, was missing the terminating NULL section, so we would run off into to woods, beyond the array limit. This would most commonly result in a segfault:
```
$ sunxi-fel sid-dump
....
00000000 00000000 00000000 00000000
Segmentation fault (core dumped)
```
Add the NULL sentinel to terminate the loop correctly.
> fel: sid: fix segfault with default section map

- fel.c
- soc_info.c
- soc_info.h
The Allwinner H616 ships in at least two die variants, sometime under a different name (H618, T507), but sometimes labeled as a normal "H616". The die variants differ in their CPU cluster control subsystem, which affects the location of the RVBAR shadow register used to reset the core into 64-bit mode. We use that in the "reset64" command, but also as part of the boot process using the "uboot" command, on ARMv8 cores.
Add code to detect the die variant by reading the VER_REG MMIO register, where the original die reports 0x00 in the lower 8 bits, but the newer die variants apparently 0x02. In the latter case let the aw_rmr_request() function use the alternative RVBAR address to do the 64-bit switch. This matches what we do in U-Boot and Trusted Firmware.
> fel: h616: support alternative die variant

- fel_lib.c
When reading from the SID device using the normal memory access method, we upload our "readl" routine (via fel_readl_n()), which expects a number of *words* to read. However length is given in *bytes*, so we read four times as much, and overflow our key buffer, clobbering the return address. This is typically fatal:
```
$ ./sunxi-fel sid
02c05200:12345678:34567890:76543210
Segmentation fault (core dumped)
$
```
Fix this by giving the number of (32-bit) words instead. We already checked that length is a multiple of 4, so we can just divide.
> fel: sid: fix stack overflow while reading from SID

- soc_info.c
The Allwinner A523 has 128KiB of MCU0 SRAM, which the BootROM will not touch. The BROM will use some memory in SRAM A2, which it also clears upon entering FEL mode, starting from address 0x44000. The lowest allocation seems to be the IRQ stack growing down from 0x45400. So we won't touch any of that memory, but can freely use the full 128KB of the primary SRAM for payloads. This means we won't need to swap any buffers for preserving BROM stacks.
We put the SPL thunk code just below 0x44000, to leave as much SRAM for the payload as possible.
The rest of the SoC is pretty standard, although the watchdogs are now in separate MMIO frames, not part of some timer block anymore.
The secure boot mode will prevent even reading the BootROM, so we can use an address in there to test for the secure …
> fel: add Allwinner A523 SoC support

- soc_info.c
- uart0-helloworld-sdboot.c
uart0-helloworld-sdcard can work with this patch:
```console
./sunxi-fel --verbose spl uart0-helloworld-sdboot.sunxi
Stack pointers: sp_irq=0x00022000, sp=0x00025E08
MMU is not enabled by BROM
=> Executing the SPL... done.
```
And next is the uart console's log:
```
Hello from Allwinner T7!
Returning back to FEL.
```
> fel: Add support for allwinner T7

- fel-remotefunc-compiler.rb
It was using a deprecated (now deleted) function to check file existence.
> Fix fel-remotefunc-compiler execution on newer Ruby versions

- soc_info.c
While playing with a proper A523 (T527, really) devboard, I noticed some issues with the FEL support: We need to disable the I-cache, to allow uploading *and* executing code via FEL.
Also the load and buffer addresses are not ideal: the BROM actually loads any MMC payload somewhere else, so we need to follow suit here to keep a single SPL image, for loading via both SD card/eMMC/SPI and via FEL.
> A523 FEL fixes

- fel_lib.c
Field has 32 bits, not 16, as it is currently handled. This fixes scratchpad address print when using "sunxi-fel ver" command on A523. Before it printed "0x1500" and afterwards "0x61500", which makes much more sense and it was verified by BROM disassembly.
> fel-lib: Fix parsing scratchpad field
